server:
  port: 8907

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
      lease:
        duration: 5
    enabled: false
endpoints:
  shutdown:
    enabled: true

spring:
  application:
    name: together-message
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL:http://localhost:9001}/admin/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

info:
  tags:
    environment: local

---
spring:
  profiles: prod

server:
  port: 8080

eureka:
  client:
    enabled: true

info:
  tags:
    environment: prod
