version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/avijitmondal
    token: ${{ github.token }}
updates:
  - package-ecosystem: "maven"
    directory: "/" 
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    labels:
      - "maven dependencies"
    commit-message:
      prefix: "maven"
    pull-request-branch-name:
      separator: "-
